const heroesData = [
  {
    id: 1,
    name: 'Toshinori Yagi',
    heroName: 'All Might',
    quirk: 'One For All',
    type: 'Emitter',
    encounteredVillainIds: [1, 4, 6],
  },
  {
    id: 2,
    name: 'Enji Todoroki',
    heroName: 'Endeavor',
    quirk: 'Hellflame',
    type: 'Emitter',
    encounteredVillainIds: [2, 6],
  },
  {
    id: 3,
    name: 'Midoriya Izuku',
    heroName: 'Deku',
    quirk: 'One For All',
    type: 'Emitter',
    encounteredVillainIds: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    id: 4,
    name: 'Eijiro Kirishima',
    heroName: 'Red Riot',
    quirk: 'Hardening',
    type: 'Transformation',
    encounteredVillainIds: [1, 4, 6, 8],
  },
  {
    id: 5,
    name: 'Tsuyu Asui',
    heroName: 'Froppy',
    quirk: 'Frog',
    type: 'Mutant',
    encounteredVillainIds: [4, 5, 6],
  },
  {
    id: 6,
    name: 'Yu Takeyama',
    heroName: 'Mt. Lady',
    quirk: 'Gigantification',
    type: 'Transformation',
    encounteredVillainIds: [1, 4, 6],
  },
  {
    id: 7,
    name: 'Tenya Iida',
    heroName: 'Ingenium',
    quirk: 'Engine',
    type: 'Mutant',
    encounteredVillainIds: [1, 2, 4, 5, 6],
  },
  {
    id: 8,
    name: 'Ryuko Tatsuma',
    heroName: 'Ryuku',
    quirk: 'Dragon',
    type: 'Transformation',
    encounteredVillainIds: [3, 5, 7],
  },
];

export default heroesData;
